name: emc_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3
  - pytorch-gpu
  - cudnn=8.8.0
  - kaleido-core=0.2.1
  - scipy
  - numpy=1.24.2
  - plotly=5.16.1
  - simple-parsing
  - tqdm
  - nibabel